"""v3 support/phase UI regression with isolated local browser state."""
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

OUT=Path('/tmp/lumbre-planner-v3'); OUT.mkdir(exist_ok=True)
with sync_playwright() as pw:
    browser=pw.chromium.launch()
    for width in (320,390,1440):
        context=browser.new_context(viewport={'width':width,'height':1000},reduced_motion='reduce')
        page=context.new_page(); errors=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.goto('http://127.0.0.1:3001/#planificador',wait_until='networkidle')
        page.add_style_tag(content='*{scroll-behavior:auto!important;animation:none!important}')
        expect(page.locator('.planner-customize')).not_to_have_attribute('open','')
        page.locator('.planner-customize > summary').click()
        page.get_by_label('Soporte del alimento',exact=True).select_option('sarten')
        page.get_by_role('button',name='Crear secuencia: indirecto → sellado',exact=True).click()
        expect(page.get_by_label('Tipo de cocción',exact=True)).to_have_value('dos_zonas')
        page.get_by_label('Temperatura de etapa 1 (°C)',exact=True).fill('120–140')
        page.get_by_label('Temperatura de etapa 2 (°C)',exact=True).fill('200')
        page.get_by_label('Soporte de etapa 2',exact=True).select_option('plancha')
        page.get_by_label('Duración o señal para cambiar 1',exact=True).fill('Señal indicada por mi receta')
        page.get_by_role('button',name='Añadir etapa',exact=True).click()
        page.get_by_label('Nombre de etapa 3',exact=True).fill('Pausa de la receta')
        page.get_by_label('Temperatura de etapa 3 (°C)',exact=True).fill('180')
        page.get_by_label('Tipo de etapa 3',exact=True).select_option('pausa')
        expect(page.get_by_label('Temperatura de etapa 3 (°C)',exact=True)).to_have_value('')
        expect(page.get_by_label('Temperatura de etapa 3 (°C)',exact=True)).to_be_disabled()
        page.get_by_role('button',name='Construir plan de fuego',exact=True).click()
        out=page.locator('.planner-result');expect(out).to_be_visible()
        expect(out.locator('.fire-stage-layout')).to_have_count(2)
        expect(out.locator('[data-stage-kind="pausa"] .fire-diagram')).to_have_count(0)
        expect(out.locator('.fire-mount[data-surface="plancha"]')).to_have_count(1)
        expect(out).to_contain_text('Señal indicada por mi receta')
        expect(out).to_contain_text('Cambio de montaje')
        for locator in (page.locator('#planificador'),page.locator('.planner-controls'),out):
            assert locator.evaluate('(e)=>e.scrollWidth<=e.clientWidth'),width
        out.locator('.fire-plan-timeline').screenshot(path=str(OUT/f'stages-{width}.png'))
        page.get_by_label('Nombre del plan',exact=True).fill('Montajes y pausa')
        page.get_by_role('button',name='Guardar plan',exact=True).click()
        page.reload(wait_until='networkidle')
        page.get_by_role('button',name='Editar plan Montajes y pausa',exact=True).click()
        expect(page.get_by_label('Soporte del alimento',exact=True)).to_have_value('sarten')
        expect(page.get_by_label('Soporte de etapa 2',exact=True)).to_have_value('plancha')
        expect(page.get_by_label('Tipo de etapa 3',exact=True)).to_have_value('pausa')
        page.get_by_role('button',name='Imprimir plan Montajes y pausa',exact=True).click()
        dialog=page.get_by_role('dialog')
        expect(dialog.locator('.fire-stage-layout')).to_have_count(2)
        expect(dialog).to_contain_text('Pausa de la receta')
        assert dialog.evaluate('(e)=>e.scrollWidth<=e.clientWidth')
        if width==1440:page.pdf(path=str(OUT/'montajes-y-pausa.pdf'),format='A4',print_background=True)
        assert not errors,errors
        context.close();print(width,'PASS',flush=True)
    context=browser.new_context()
    page=context.new_page()
    page.add_init_script('localStorage.setItem("lumbre.fire-planner.presets.v1", JSON.stringify([{id:"old",name:"Montaje antiguo",configuration:{equipment:"kettle",fuelType:"carbon",cookingStyle:"directo",accessory:"Plancha especial"}}]))')
    page.goto('http://127.0.0.1:3001',wait_until='networkidle')
    page.get_by_role('button',name='Editar plan Montaje antiguo',exact=True).click()
    expect(page.get_by_label('Soporte del alimento',exact=True)).to_have_value('sin_definir')
    expect(page.locator('.planner-result')).to_contain_text('El soporte no está representado')
    expect(page.locator('.planner-result .fire-mount svg')).to_have_count(0)
    expect(page.locator('[name="accessory"]')).to_have_value('Plancha especial')
    context.close();print('PASS legacy accessory is not guessed',flush=True)
    browser.close()
