"""Inspect PDFs generated by test-static.py (requires pypdf)."""
from pathlib import Path
from pypdf import PdfReader

for name in [f"product-{index}" for index in range(1, 5)] + ["experiment"] + [f"recipe-{index}" for index in range(1, 4)]:
    path = Path("/tmp") / f"lumbre-print-{name}.pdf"
    reader = PdfReader(path)
    texts = [(page.extract_text() or "").strip() for page in reader.pages]
    assert 1 <= len(texts) <= 3, (name, "Unexpected page count", len(texts))
    assert all(len(text) > 80 for text in texts), (name, "Blank or almost empty page")
    assert all("El fuego nos" not in text for text in texts), "Portal leaked into print"
    combined = " ".join(" ".join(texts).split())
    if name.startswith("product"):
        assert "Al llevarlo al fuego" in combined, "Last section is missing"
        assert "Umami" in combined, "Chart content is missing"
    elif name == "experiment":
        assert "registrada el" in combined.lower(), "Experimental sheet footer is missing"
    else:
        assert "Preparación paso a paso" in combined, "Recipe instructions are missing"
        assert "Notas y fuentes" in combined, "Recipe sources are missing"
    print(f"PASS {name}: {len(texts)} pages; text lengths {[len(text) for text in texts]}")
