"""Primary controls and editable temperature suggestions, without advanced setup."""
from playwright.sync_api import sync_playwright, expect

with sync_playwright() as pw:
    browser = pw.chromium.launch()
    for width in (390, 1440):
        page = browser.new_page(viewport={'width': width, 'height': 1000})
        page.goto('http://127.0.0.1:3001/#planificador', wait_until='domcontentloaded')
        temp = page.get_by_label('Temperatura de trabajo', exact=True)
        hours = page.get_by_label('Horas de cocción', exact=True)
        details = page.locator('.planner-customize')
        expect(temp).to_have_value('220')
        expect(hours).to_be_visible()
        assert not details.evaluate('e=>e.open')
        for goal, expected in [('ahumar','120'),('hornear','180'),('asar','220')]:
            page.get_by_label('Objetivo de cocción', exact=True).select_option(goal)
            expect(temp).to_have_value(expected)
        page.get_by_label('Tipo de cocción', exact=True).select_option('indirecto')
        expect(temp).to_have_value('200')
        page.get_by_label('Tipo de cocción', exact=True).select_option('dos_zonas')
        expect(temp).to_have_value('200')
        temp.fill('175')
        page.get_by_label('Objetivo de cocción', exact=True).select_option('hornear')
        expect(temp).to_have_value('175')
        page.get_by_role('button', name='Usar sugerida', exact=True).click()
        expect(temp).to_have_value('180')
        hours.fill('2.5')
        expect(page.get_by_role('button', name='Imprimir / PDF', exact=True)).to_have_count(0)
        page.get_by_role('button', name='Construir plan de fuego', exact=True).click()
        expect(page.locator('.planner-result')).to_be_visible()
        expect(page.locator('.planner-result')).to_contain_text('2.5 h')
        expect(page.locator('.planner-result')).to_contain_text('180 °C · sugerida')
        page.get_by_role('button', name='Imprimir / PDF', exact=True).click()
        expect(page.get_by_role('dialog')).to_be_visible()
        expect(page.locator('#fire-plan-title')).to_have_text('Mi plan de fuego')
        expect(page.locator('.fire-plan-print')).to_contain_text('2.5 h')
        expect(page.get_by_role('button', name='Imprimir ficha', exact=True)).to_be_visible()
        expect(page.locator('[data-testid="fire-presets"] article')).to_have_count(0)
        page.get_by_role('button', name='Cerrar plan imprimible', exact=True).click()
        hours.fill('3')
        expect(page.get_by_role('button', name='Imprimir / PDF', exact=True)).to_have_count(0)
        hours.fill('2.5')
        page.get_by_role('button', name='Construir plan de fuego', exact=True).click()
        page.get_by_label('Nombre del plan', exact=True).fill('Plan sencillo')
        page.get_by_role('button', name='Guardar plan', exact=True).click()
        page.reload(wait_until='domcontentloaded')
        page.get_by_role('button', name='Editar plan Plan sencillo', exact=True).click()
        expect(hours).to_have_value('2.5')
        expect(temp).to_have_value('180')
        assert not details.evaluate('e=>e.open')
        details.locator('summary').click()
        page.get_by_label('Unidad de temperatura', exact=True).select_option('F')
        expect(temp).to_have_value('356')
        assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
        page.screenshot(path=f'/tmp/planner-simple-{width}.png', full_page=False)
        print('PASS', width, 'primary controls, defaults, overrides, saved plans, units', flush=True)
        page.close()
    browser.close()
