import { Mount, StageTimeline } from "./fire-plan-mount";
import Diagram from "./fire-plan-illustration";
import FuelEstimate from "./fire-plan-fuel";
import { type Configuration, equipmentLabels, fuelLabels, methodLabels, issues, guide, fuelGuidance, safeRecipeUrl, goalLabels, goalHelp, hasSmoke } from "./fire-plan-model";
export default function PlanGuide({ configuration: c }: {
    configuration: Configuration;
}) {
    const problems = issues(c), plan = guide(c);
    if (problems.length)
        return <div className="fire-plan-caution"><h3>Revisión necesaria</h3><ul>{problems.map(p => <li key={p}>{p}</li>)}</ul></div>;
    const pending = [!c.temperature && !c.stages.some(s => s.temperature) ? "Temperatura de trabajo: consulta tu receta." : "", !c.durationHours ? "Tiempo de fuego: sin definir; no se calcula consumo." : "", c.cookingStyle === "dos_zonas" && !c.stages.length ? "Orden de uso de las zonas: añade etapas si quieres repetirlo." : ""].filter(Boolean);
    return <div className="fire-plan-guide"><FuelEstimate c={c}/><p className="section-index">CONFIGURACIÓN ELEGIDA / NO ES UNA MEDICIÓN</p>
    <p>{goalHelp[c.goal]}</p><dl className="fire-plan-facts"><div><dt>Objetivo</dt><dd>{goalLabels[c.goal]}{c.stages.some(s => s.goal && s.goal !== c.goal && s.kind !== "pausa") ? " · ver objetivos por etapa" : ""}</dd></div><div><dt>Equipo</dt><dd>{equipmentLabels[c.equipment]}</dd></div><div><dt>Combustible</dt><dd>{fuelLabels[c.fuelType]}</dd></div><div><dt>Método</dt><dd>{methodLabels[c.cookingStyle]}{hasSmoke(c) ? " + aporte de humo" : ""}</dd></div><div><dt>Horas de cocción previstas</dt><dd>{c.durationHours ? c.durationHours + " h" : "Sin definir"}</dd></div><div><dt>Temperatura de trabajo</dt><dd>{c.temperature ? c.temperature + " °" + c.unit + (c.temperatureSuggested ? " · sugerida, ajustar a receta" : "") : c.stages.some(s => s.temperature) ? "Ver etapas" : "Pendiente de receta"}</dd></div><div><dt>Accesorios / montaje</dt><dd>{c.accessory || "Según el esquema y el manual"}</dd></div></dl>
    <div className="fire-plan-layout"><Diagram c={c}/><div><h3>{plan.layout}</h3><p>{c.equipment === "abierta" ? "La zona libre sirve para retirar el alimento del fuego; no proporciona cocción de horno." : c.equipment === "kamado" && c.cookingStyle === "dos_zonas" ? "Usa el reparto de rejillas y deflectores admitido por el modelo. Cambiar de etapa no autoriza mover cerámica caliente con las manos." : "Comprueba la posición del alimento y la separación del calor antes de encender. Usa los accesorios previstos por el fabricante."}</p></div></div>
    {!c.stages.length && <Mount c={c}/>}
    <ol className="fire-plan-steps"><li><h3>01 / Prepara</h3><p>{plan.preparation}</p><p>Ten pinzas, guantes térmicos y termómetro. {c.durationHours ? "Prevés cocinar durante " + c.durationHours + " h. Añade tiempo de encendido y precalentamiento; esta duración no garantiza el punto del alimento ni determina recargas." : "Define en tu receta cuánto tiempo necesitarás cocinar."}</p></li><li><h3>02 / Enciende</h3><p>{c.equipment === "pellets" ? "Comprueba el suministro eléctrico y sigue el arranque del controlador según el manual. No enciendas una carga manual de pellets ni improvises un reinicio tras un fallo." : c.equipment === "gas" ? "Abre la tapa y sigue la secuencia de encendido del fabricante. Si no enciende o percibes olor a gas, detente y sigue su procedimiento de seguridad." : "Enciende la porción de combustible indicada por el procedimiento del modelo. Mantén las entradas de aire libres; cargar y encender son decisiones distintas."}</p><p>Espera a que el calor se estabilice. {c.temperature ? "Tu objetivo anotado es " + c.temperature + " °" + c.unit + "; compruébalo con termómetro y dentro del rango admitido por tu equipo." : "Consulta en la receta la temperatura de trabajo antes de colocar el alimento."}</p></li><li><h3>03 / Controla</h3><p>{plan.control}</p><p>{c.equipment === "pellets" ? "Mantén los pellets secos y vigila su nivel. No desconectes el equipo para sustituir su ciclo normal de apagado." : c.equipment === "gas" ? "Vigila el suministro; no cambies el tipo de gas." : "Recarga sólo según la evolución del fuego y el procedimiento del equipo; no por un intervalo universal."}</p></li><li><h3>04 / Aprende</h3><p>Registra combustible utilizado, recargas y respuesta del equipo en las notas. Edita este plan guardado para conservar lo aprendido.</p><p>La temperatura del asador no indica el punto seguro del alimento: sigue una receta fiable y compruébalo con termómetro.</p></li></ol>
    {c.stages.length > 0 && <StageTimeline c={c} renderDiagram={stage => <Diagram c={stage}/>}/>}
    {hasSmoke(c) && <p className="fire-plan-caution"><strong>Ahumado:</strong> {c.smokeWood || "Madera sin especificar"}. {c.equipment === "pellets" ? "Los pellets aportan calor y humo; no añadas leña al quemador ni presupongas que necesita un accesorio adicional." : c.equipment === "gas" ? "Sólo en el accesorio autorizado por el fabricante, nunca como combustible principal ni sobre quemadores." : "Usa únicamente madera apta para cocinar y la cantidad admitida por el modelo; no sustituye automáticamente el combustible principal."}</p>}
    {pending.length > 0 && <aside className="fire-plan-pending"><h3>Antes de encender, completa o consulta</h3><ul>{pending.map(p => <li key={p}>{p}</li>)}</ul></aside>}
    {c.recipeUrl && safeRecipeUrl(c.recipeUrl) && <p className="fire-plan-source"><strong>Tu receta / referencia:</strong> <a href={c.recipeUrl} target="_blank" rel="noreferrer">{c.recipeUrl}</a><small>Enlace aportado por ti; su contenido no ha sido verificado por el planificador.</small></p>}
    {c.notes && <section className="fire-plan-notes"><h3>Notas y observaciones</h3><p className="preserve-lines">{c.notes}</p></section>}
    <p className="fire-plan-safety"><strong>Siempre al aire libre y bajo vigilancia.</strong> Nunca en interiores, garajes o espacios cerrados. Mantén distancia de puertas, ventanas y materiales combustibles. Si el viento hace inseguro el uso, pospón la sesión.</p>
    <details><summary>Compatibilidad, alcance y fuentes</summary><p>{fuelGuidance(c.equipment)} Calcula un presupuesto de combustible cuando hay consumo de referencia o un dato aportado por ti. No calcula raciones ni hora de servicio. Las temperaturas sugeridas son puntos de partida editables, no recetas ni temperaturas internas seguras. Las etapas y valores personalizados son datos del usuario. Los registros antiguos se conservan; personas, clima y hora de servicio no producen cálculos.</p><ul><li><a href="https://www.weber.com/GB/en/blog/charcoal-barbecuing/how-to-control-the-temperature-of-your-charcoal-barbecue/weber-257648.html" target="_blank" rel="noreferrer">Weber: rangos de calor de referencia</a></li><li><a href="https://content-images.weber.com/downloads/Genesis-E-425-E-435-EP-435-SP-435-Quick-setting-guide-FINAL.pdf" target="_blank" rel="noreferrer">Weber: rango bajo para cocción lenta</a></li><li><a href="https://www.kamadojoe.com/blogs/kamado-joe-blog/beat-the-heat-how-to-maintain-consistent-temps-when-it-s-hot-out" target="_blank" rel="noreferrer">Kamado Joe: carga, encendido y control de calor</a></li><li><a href="https://www.weber.com/US/en/grill-skills/mastering-smoke/smoker-setup/smoking-on-a-charcoal-grill/weber-34482.html" target="_blank" rel="noreferrer">Weber: disposición para ahumar con carbón</a></li><li><a href="https://contact-emea.weber.com/hc/en-us/articles/360000632217-How-to-Light-a-Smokey-Mountain-Cooker" target="_blank" rel="noreferrer">Weber: ahumador vertical</a></li></ul></details>
  </div>;
}
