import { Mount, StageTimeline } from "./fire-plan-mount";
import TechnicalDiagram from "./fire-plan-diagram";
import ExtendedDiagram from "./fire-plan-diagram-extended";
import { type Configuration, equipmentLabels, fuelLabels, methodLabels, issues, guide, fuelGuidance, safeRecipeUrl } from "./fire-plan-model";
function Diagram({ c }: { c: Configuration }) {
    if (["kamado", "ahumador", "abierta"].includes(c.equipment)) return <ExtendedDiagram c={c}/>;
    return c.equipment === "kettle" || c.equipment === "gas" || (c.equipment === "offset" && c.cookingStyle === "indirecto")
        ? <TechnicalDiagram c={c}/> : <LegacyDiagram c={c}/>;
}
function LegacyDiagram({ c }: {
    c: Configuration;
}) {
    const indirect = c.cookingStyle === "indirecto", combined = c.cookingStyle === "dos_zonas";
    const vertical = c.equipment === "kamado" || c.equipment === "ahumador";
    return <figure className="fire-diagram"><svg viewBox="0 0 300 200" role="img" aria-label={guide(c).layout + ". Negro: alimento; rojo: calor activo; vacío: zona sin encender."}>
    {c.equipment === "offset" && indirect ? <><rect x="12" y="90" width="66" height="65" rx="8" fill="none" stroke="currentColor" strokeWidth="2"/><rect x="92" y="35" width="192" height="115" rx="28" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M78 120H92 M240 35V14" stroke="currentColor" strokeWidth="4"/><path d="M29 132H61" stroke="#7b251b" strokeWidth="12"/><path d="M125 99H253" stroke="currentColor"/><ellipse cx="182" cy="83" rx="25" ry="10" fill="currentColor"/><path d="M102 117H145L137 110 M145 117L137 124" fill="none" stroke="#7b251b" strokeWidth="2"/><text x="45" y="182" textAnchor="middle">FUEGO</text><text x="184" y="182" textAnchor="middle">ALIMENTO EN CÁMARA</text></>
            : vertical ? <><path d="M40 151V66Q40 15 150 15Q260 15 260 66V151Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M56 75H244" stroke="currentColor"/><ellipse cx={combined ? 100 : 150} cy="59" rx="22" ry="9" fill="currentColor"/>{combined && <ellipse cx="200" cy="59" rx="22" ry="9" fill="none" stroke="currentColor" strokeWidth="2"/>}{(indirect || combined) && <path d={combined ? "M163 99H238" : "M64 99H236"} stroke="currentColor" strokeWidth="7"/>}<path d="M87 130H130" stroke="#7b251b" strokeWidth="12"/><rect x="150" y="123" width="58" height="14" fill="none" stroke="currentColor" strokeDasharray="4 3"/><text x="150" y="176" textAnchor="middle">{indirect ? "SEPARACIÓN INDIRECTA" : combined ? "DOS ZONAS / SEGÚN MODELO" : "MONTAJE DIRECTO"}</text></>
                : <><rect x="18" y="24" width="264" height="130" rx="36" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M145 35V144" stroke="currentColor" strokeDasharray="4 4"/>{c.equipment === "gas" ? <><path d="M60 92V131 M99 92V131" stroke="#7b251b" strokeWidth="9"/><rect x="182" y="92" width="9" height="39" fill="none" stroke="currentColor"/><rect x="220" y="92" width="9" height="39" fill="none" stroke="currentColor"/></> : [0, 1].flatMap(row => [0, 1, 2].map(col => <circle key={row + "-" + col} cx={55 + col * 26} cy={103 + row * 25} r="9" fill="#7b251b"/>))}<ellipse cx={indirect ? 205 : 75} cy="65" rx="24" ry="10" fill="currentColor"/>{combined && <><ellipse cx="205" cy="65" rx="24" ry="10" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M113 64H162L155 57 M162 64L155 71" stroke="currentColor" fill="none"/></>}<text x="80" y="181" textAnchor="middle">CALOR ACTIVO</text><text x="212" y="181" textAnchor="middle">SIN ENCENDER</text></>}
  </svg><figcaption>● Alimento · rojo: calor activo · vacío: zona sin encender{vertical && " · barra: deflector/separador"}. Reserva sin encender sólo según el procedimiento del modelo. Esquema conceptual, no cantidades ni plano de montaje.</figcaption></figure>;
}
export default function PlanGuide({ configuration: c }: {
    configuration: Configuration;
}) {
    const problems = issues(c), plan = guide(c);
    if (problems.length)
        return <div className="fire-plan-caution"><h3>Revisión necesaria</h3><ul>{problems.map(p => <li key={p}>{p}</li>)}</ul></div>;
    const pending = [!c.temperature && !c.stages.some(s => s.temperature) ? "Temperatura de trabajo: consulta tu receta." : "", !c.durationHours ? "Tiempo de fuego: sin definir; no se calcula consumo." : "", c.cookingStyle === "dos_zonas" && !c.stages.length ? "Orden de uso de las zonas: añade etapas si quieres repetirlo." : ""].filter(Boolean);
    return <div className="fire-plan-guide"><p className="section-index">CONFIGURACIÓN ELEGIDA / NO ES UNA MEDICIÓN</p>
    <dl className="fire-plan-facts"><div><dt>Equipo</dt><dd>{equipmentLabels[c.equipment]}</dd></div><div><dt>Combustible</dt><dd>{fuelLabels[c.fuelType]}</dd></div><div><dt>Método</dt><dd>{methodLabels[c.cookingStyle]}{c.smoking ? " + ahumado" : ""}</dd></div><div><dt>Tiempo con fuego</dt><dd>{c.durationHours ? c.durationHours + " h" : "Sin definir"}</dd></div><div><dt>Temperatura de trabajo</dt><dd>{c.temperature ? c.temperature + " °" + c.unit : c.stages.some(s => s.temperature) ? "Ver etapas" : "Pendiente de receta"}</dd></div><div><dt>Accesorios / montaje</dt><dd>{c.accessory || "Según el esquema y el manual"}</dd></div></dl>
    <div className="fire-plan-layout"><Diagram c={c}/><div><h3>{plan.layout}</h3><p>{c.equipment === "abierta" ? "La zona libre sirve para retirar el alimento del fuego; no proporciona cocción de horno." : c.equipment === "kamado" && c.cookingStyle === "dos_zonas" ? "Usa el reparto de rejillas y deflectores admitido por el modelo. Cambiar de etapa no autoriza mover cerámica caliente con las manos." : "Comprueba la posición del alimento y la separación del calor antes de encender. Usa los accesorios previstos por el fabricante."}</p></div></div>
    {!c.stages.length && <Mount c={c}/>}
    <ol className="fire-plan-steps"><li><h3>01 / Prepara</h3><p>{plan.preparation}</p><p>Ten pinzas, guantes térmicos y termómetro. {c.durationHours ? "Reserva una ventana de " + c.durationHours + " h para vigilar el fuego; no equivale al tiempo de cocción ni determina recargas." : "Define en tu receta cuánto tiempo necesitarás cocinar."}</p></li><li><h3>02 / Enciende</h3><p>{c.equipment === "gas" ? "Abre la tapa y sigue la secuencia de encendido del fabricante. Si no enciende o percibes olor a gas, detente y sigue su procedimiento de seguridad." : "Enciende la porción de combustible indicada por el procedimiento del modelo. Mantén las entradas de aire libres; cargar y encender son decisiones distintas."}</p><p>Espera a que el calor se estabilice. {c.temperature ? "Tu objetivo anotado es " + c.temperature + " °" + c.unit + "; compruébalo con termómetro y dentro del rango admitido por tu equipo." : "Consulta en la receta la temperatura de trabajo antes de colocar el alimento."}</p></li><li><h3>03 / Controla</h3><p>{plan.control}</p><p>{c.equipment === "gas" ? "Vigila el suministro; no cambies el tipo de gas." : "Recarga sólo según la evolución del fuego y el procedimiento del equipo; no por un intervalo universal."}</p></li><li><h3>04 / Aprende</h3><p>Registra combustible utilizado, recargas y respuesta del equipo en las notas. Edita este plan guardado para conservar lo aprendido.</p><p>La temperatura del asador no indica el punto seguro del alimento: sigue una receta fiable y compruébalo con termómetro.</p></li></ol>
    {c.stages.length > 0 && <StageTimeline c={c} renderDiagram={stage => <Diagram c={stage}/>}/>}
    {c.smoking && <p className="fire-plan-caution"><strong>Ahumado:</strong> {c.smokeWood || "Madera sin especificar"}. {c.equipment === "gas" ? "Sólo en el accesorio autorizado por el fabricante, nunca como combustible principal ni sobre quemadores." : "Usa únicamente madera apta para cocinar y la cantidad admitida por el modelo; no sustituye automáticamente el combustible principal."}</p>}
    {pending.length > 0 && <aside className="fire-plan-pending"><h3>Antes de encender, completa o consulta</h3><ul>{pending.map(p => <li key={p}>{p}</li>)}</ul></aside>}
    {c.recipeUrl && safeRecipeUrl(c.recipeUrl) && <p className="fire-plan-source"><strong>Tu receta / referencia:</strong> <a href={c.recipeUrl} target="_blank" rel="noreferrer">{c.recipeUrl}</a><small>Enlace aportado por ti; su contenido no ha sido verificado por el planificador.</small></p>}
    {c.notes && <section className="fire-plan-notes"><h3>Notas y observaciones</h3><p className="preserve-lines">{c.notes}</p></section>}
    <p className="fire-plan-safety"><strong>Siempre al aire libre y bajo vigilancia.</strong> Nunca en interiores, garajes o espacios cerrados. Mantén distancia de puertas, ventanas y materiales combustibles. Si el viento hace inseguro el uso, pospón la sesión.</p>
    <details><summary>Compatibilidad, alcance y fuentes</summary><p>{fuelGuidance(c.equipment)} No calcula kilos, raciones ni hora de servicio. Las temperaturas y etapas anotadas son datos del usuario, no recomendaciones validadas. Los registros antiguos se conservan; personas, clima y hora de servicio no producen cálculos.</p><ul><li><a href="https://www.kamadojoe.com/blogs/kamado-joe-blog/beat-the-heat-how-to-maintain-consistent-temps-when-it-s-hot-out" target="_blank" rel="noreferrer">Kamado Joe: carga, encendido y control de calor</a></li><li><a href="https://www.weber.com/US/en/grill-skills/mastering-smoke/smoker-setup/smoking-on-a-charcoal-grill/weber-34482.html" target="_blank" rel="noreferrer">Weber: disposición para ahumar con carbón</a></li><li><a href="https://contact-emea.weber.com/hc/en-us/articles/360000632217-How-to-Light-a-Smokey-Mountain-Cooker" target="_blank" rel="noreferrer">Weber: ahumador vertical</a></li></ul></details>
  </div>;
}
