-- Preserve historical products and orders; only retire their public listings.
--> statement-breakpoint
ALTER TABLE catalog_products ADD COLUMN details TEXT;
--> statement-breakpoint
UPDATE catalog_products SET details = '{"productCode":"LMB-F-001","description":"Mezcla multiuso de sal de mar, pimienta negra molida y ajo granulado para preparaciones a la parrilla.","components":[{"id":"sal_mar_gruesa","nombre":"Sal de mar","familia":"Sal"},{"id":"pimienta_negra","nombre":"Pimienta negra molida","familia":"Pimienta"},{"id":"ajo_granulado","nombre":"Ajo granulado","familia":"Allium"}],"image":"/editorial/products/lmb-f-001.jpeg","imageAlt":"Frasco LMB-F-001, Sazonador multiuso Lumbre","netContent":"150 g"}', price = 99, revision = revision + 1, updated_at = CURRENT_TIMESTAMP WHERE id = 121;
--> statement-breakpoint
UPDATE catalog_products SET details = '{"productCode":"LMB-F-002","description":"Mezcla para carne de res elaborada con sal de mar, pimienta negra molida y hongo shiitake molido.","components":[{"id":"sal_mar_gruesa","nombre":"Sal de mar","familia":"Sal"},{"id":"pimienta_negra","nombre":"Pimienta negra molida","familia":"Pimienta"},{"id":"shiitake_seco","nombre":"Hongo shiitake molido","familia":"Umami"}],"image":"/editorial/products/lmb-f-002.jpeg","imageAlt":"Frasco LMB-F-002, Sazonador para carne de res Lumbre","netContent":"150 g"}', price = 99, revision = revision + 1, updated_at = CURRENT_TIMESTAMP WHERE id = 122;
--> statement-breakpoint
UPDATE catalog_products SET details = '{"productCode":"LMB-F-003","description":"Mezcla para carne de cerdo elaborada con sal de mar, azúcar mascabado, pimienta negra molida, ajo granulado y chile pasilla molido.","components":[{"id":"sal_mar_gruesa","nombre":"Sal de mar","familia":"Sal"},{"id":"azucar_morena","nombre":"Azúcar mascabado","familia":"Endulzante"},{"id":"pimienta_negra","nombre":"Pimienta negra molida","familia":"Pimienta"},{"id":"ajo_granulado","nombre":"Ajo granulado","familia":"Allium"},{"id":"chile_pasilla","nombre":"Chile pasilla molido","familia":"Chile"}],"image":"/editorial/products/lmb-f-003.jpeg","imageAlt":"Frasco LMB-F-003, Sazonador para carne de cerdo Lumbre","netContent":"150 g"}', price = 99, revision = revision + 1, updated_at = CURRENT_TIMESTAMP WHERE id = 123;
--> statement-breakpoint
UPDATE catalog_products SET details = '{"productCode":"LMB-F-004","description":"Mezcla para carne de pollo elaborada con sal de mar, pimienta negra molida, ajo granulado, comino y sumac.","components":[{"id":"sal_mar_gruesa","nombre":"Sal de mar","familia":"Sal"},{"id":"pimienta_negra","nombre":"Pimienta negra molida","familia":"Pimienta"},{"id":"ajo_granulado","nombre":"Ajo granulado","familia":"Allium"},{"id":"comino","nombre":"Comino","familia":"Semilla_aromatica"},{"id":"sumac","nombre":"Sumac","familia":"Citrico"}],"image":"/editorial/products/lmb-f-004.jpeg","imageAlt":"Frasco LMB-F-004, Sazonador para carne de pollo Lumbre","netContent":"150 g"}', price = 99, revision = revision + 1, updated_at = CURRENT_TIMESTAMP WHERE id = 124;
--> statement-breakpoint
UPDATE catalog_products SET active = 0, revision = revision + 1, updated_at = CURRENT_TIMESTAMP WHERE id IN (101,102,103,104,111,112,113);
--> statement-breakpoint
CREATE UNIQUE INDEX catalog_products_code_unique ON catalog_products (json_extract(details, '$.productCode')) WHERE details IS NOT NULL;
